#Flow
fast_dev_run: false
experimnet_name: ''
seed: 1234
check_val_every_n_epoch: 5000


# Net architecture
intermediate_sizes: [ ]
ptretrained_path: ../train_erm_model_20210319_183441/model.ckpt

data:
  model_degree: 7
  x_train: [ -0.85, -0.65, -0.45, 0.15, 0.25, 0.35, 0.45, 0.55, 0.65, 0.9 ]
  y_train: [ -0.6, -1.0, -0.5, -0.3, 0.1, 0.65, 0.7, 0.5, 0.2, 0.1 ]
  x_test_max: 1.0
  x_test_min: -1.0
  dx_test: 0.01
  insert_loc: 0

optim:
  lr: 0.1
  epochs: 20001
  milestones: [ 10000,19000 ]
  train_batch_size: 2
  test_batch_size: 10
  num_workers: 0

hydra:
  sweep:
    dir: ../output/multirun_${experimnet_name}_${now:%Y%m%d_%H%M%S}
    subdir: ${hydra.job.override_dirname}
  run:
    # Output directory for normal runs
    dir: ../output/${experimnet_name}_${now:%Y%m%d_%H%M%S}
